# Site settings
name: Govind Raj
title: Govind Raj | Embedded system Engineer
description: Design-minded embedded system engineer focused on building and controlling embedded devices.
url: https://gov466.github.io/
baseurl: ''
email: govind.mndy@gmail.com
cover: https://gov466.github.io/img/og.png
logo: https://gov466.github.io/img/emojis/technologist.png
resume: https://gov466.github.io/resume.pdf
social:
  - title: email
    url: mailto:govind.mndy@gmail.com
  - title: twitter
    url: https://twitter.com/Govindraj3s
  - title: instagram
    url: https://instagram.com/Govindraj7809
  - title: youtube
    url: https://www.youtube.com/channel/UCLrUNAP-yM7PjYVxOGOgB6w/videos?view=57&flow=grid
  - title: github
    url: https://github.com/gov466
  - title: linkedin
    url: https://www.linkedin.com/in/govind-raj-4b80b9135/

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
